name: PR Build

on:
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20.x

            - name: Install dependencies
              run: npm ci

            - name: Compile the project
              run: npm run compile
